# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aaron/workspace/mod_q

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aaron/workspace/mod_q

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/workspace/mod_q/CMakeFiles /home/aaron/workspace/mod_q/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/workspace/mod_q/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mod_q

# Build rule for target.
mod_q: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_q
.PHONY : mod_q

# fast build rule for target.
mod_q/fast:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/build
.PHONY : mod_q/fast

DefaultBackend.o: DefaultBackend.cpp.o
.PHONY : DefaultBackend.o

# target to build an object file
DefaultBackend.cpp.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/DefaultBackend.cpp.o
.PHONY : DefaultBackend.cpp.o

DefaultBackend.i: DefaultBackend.cpp.i
.PHONY : DefaultBackend.i

# target to preprocess a source file
DefaultBackend.cpp.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/DefaultBackend.cpp.i
.PHONY : DefaultBackend.cpp.i

DefaultBackend.s: DefaultBackend.cpp.s
.PHONY : DefaultBackend.s

# target to generate assembly for a file
DefaultBackend.cpp.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/DefaultBackend.cpp.s
.PHONY : DefaultBackend.cpp.s

ajp_backend.o: ajp_backend.cpp.o
.PHONY : ajp_backend.o

# target to build an object file
ajp_backend.cpp.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_backend.cpp.o
.PHONY : ajp_backend.cpp.o

ajp_backend.i: ajp_backend.cpp.i
.PHONY : ajp_backend.i

# target to preprocess a source file
ajp_backend.cpp.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_backend.cpp.i
.PHONY : ajp_backend.cpp.i

ajp_backend.s: ajp_backend.cpp.s
.PHONY : ajp_backend.s

# target to generate assembly for a file
ajp_backend.cpp.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_backend.cpp.s
.PHONY : ajp_backend.cpp.s

ajp_header.o: ajp_header.c.o
.PHONY : ajp_header.o

# target to build an object file
ajp_header.c.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_header.c.o
.PHONY : ajp_header.c.o

ajp_header.i: ajp_header.c.i
.PHONY : ajp_header.i

# target to preprocess a source file
ajp_header.c.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_header.c.i
.PHONY : ajp_header.c.i

ajp_header.s: ajp_header.c.s
.PHONY : ajp_header.s

# target to generate assembly for a file
ajp_header.c.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_header.c.s
.PHONY : ajp_header.c.s

ajp_link.o: ajp_link.c.o
.PHONY : ajp_link.o

# target to build an object file
ajp_link.c.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_link.c.o
.PHONY : ajp_link.c.o

ajp_link.i: ajp_link.c.i
.PHONY : ajp_link.i

# target to preprocess a source file
ajp_link.c.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_link.c.i
.PHONY : ajp_link.c.i

ajp_link.s: ajp_link.c.s
.PHONY : ajp_link.s

# target to generate assembly for a file
ajp_link.c.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_link.c.s
.PHONY : ajp_link.c.s

ajp_msg.o: ajp_msg.c.o
.PHONY : ajp_msg.o

# target to build an object file
ajp_msg.c.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_msg.c.o
.PHONY : ajp_msg.c.o

ajp_msg.i: ajp_msg.c.i
.PHONY : ajp_msg.i

# target to preprocess a source file
ajp_msg.c.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_msg.c.i
.PHONY : ajp_msg.c.i

ajp_msg.s: ajp_msg.c.s
.PHONY : ajp_msg.s

# target to generate assembly for a file
ajp_msg.c.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_msg.c.s
.PHONY : ajp_msg.c.s

ajp_utils.o: ajp_utils.c.o
.PHONY : ajp_utils.o

# target to build an object file
ajp_utils.c.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_utils.c.o
.PHONY : ajp_utils.c.o

ajp_utils.i: ajp_utils.c.i
.PHONY : ajp_utils.i

# target to preprocess a source file
ajp_utils.c.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_utils.c.i
.PHONY : ajp_utils.c.i

ajp_utils.s: ajp_utils.c.s
.PHONY : ajp_utils.s

# target to generate assembly for a file
ajp_utils.c.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/ajp_utils.c.s
.PHONY : ajp_utils.c.s

mod_proxy_ajp.o: mod_proxy_ajp.c.o
.PHONY : mod_proxy_ajp.o

# target to build an object file
mod_proxy_ajp.c.o:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/mod_proxy_ajp.c.o
.PHONY : mod_proxy_ajp.c.o

mod_proxy_ajp.i: mod_proxy_ajp.c.i
.PHONY : mod_proxy_ajp.i

# target to preprocess a source file
mod_proxy_ajp.c.i:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/mod_proxy_ajp.c.i
.PHONY : mod_proxy_ajp.c.i

mod_proxy_ajp.s: mod_proxy_ajp.c.s
.PHONY : mod_proxy_ajp.s

# target to generate assembly for a file
mod_proxy_ajp.c.s:
	$(MAKE) -f CMakeFiles/mod_q.dir/build.make CMakeFiles/mod_q.dir/mod_proxy_ajp.c.s
.PHONY : mod_proxy_ajp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mod_q"
	@echo "... rebuild_cache"
	@echo "... DefaultBackend.o"
	@echo "... DefaultBackend.i"
	@echo "... DefaultBackend.s"
	@echo "... ajp_backend.o"
	@echo "... ajp_backend.i"
	@echo "... ajp_backend.s"
	@echo "... ajp_header.o"
	@echo "... ajp_header.i"
	@echo "... ajp_header.s"
	@echo "... ajp_link.o"
	@echo "... ajp_link.i"
	@echo "... ajp_link.s"
	@echo "... ajp_msg.o"
	@echo "... ajp_msg.i"
	@echo "... ajp_msg.s"
	@echo "... ajp_utils.o"
	@echo "... ajp_utils.i"
	@echo "... ajp_utils.s"
	@echo "... mod_proxy_ajp.o"
	@echo "... mod_proxy_ajp.i"
	@echo "... mod_proxy_ajp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

